name: mpos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.6.0
  objectbox_flutter_libs: any

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.39
  csv: ^5.0.1
  path_provider: ^2.0.11
  file_picker: ^5.0.0
  http: ^0.13.5
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
