name: mpos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^1.6.0
  objectbox_flutter_libs: any

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  intl: ^0.19.0
  syncfusion_flutter_charts: ^25.2.6
  csv: ^6.0.0
  path_provider: ^2.0.11
  file_picker: ^8.0.3
  http: ^1.2.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  objectbox_generator: any

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
